src/config/routes.rb
Conductor::Application.routes.draw do

  resource :user_sessions
  match 'login',       :to => 'user_sessions#new',     :as => 'login'
  match 'logout',      :to => 'user_sessions#destroy', :as => 'logout'
  match 'register',    :to => 'users#new',             :as => 'register'

  resource  'account', :to => 'users'

  resources :password_resets, :only => [:create, :edit, :update]
  resources :username_recoveries, :only => [:create]

  resources :templates
  resources :permissions do
    collection do
      get :list
      delete :multi_destroy
      post :multi_update
      post :filter
      post :filter_entities
      post :profile_filter
    end
  end

  resources :settings do
    collection do
      get :self_service
    end
  end
  resources :pools do
    delete :multi_destroy, :on => :collection
    post :filter, :on => :collection

    resource :provider_selection, :only => [:show] do
      resources :provider_priority_groups, :except => [:show]

      match ':strategy_name/toggle', :to => 'provider_selections#toggle_strategy', :as => 'toggle_strategy'
      match ':strategy_name/edit', :to => 'provider_selections#edit_strategy', :as => 'edit_strategy'
      match ':strategy_name/save_strategy_options', :to => 'provider_selections#save_strategy_options', :as => 'save_strategy_options'
    end
  end

  resources :deployments do
    collection do
      get 'multi_stop'
      delete :multi_destroy
      get 'launch_new'
      post 'launch_time_params'
      get 'launch_time_params'
      post 'overview'
      get 'check_name'
      get 'launch_from_catalog'
      post 'filter'
    end
    resources :instances
  end

  resources :instances do
    collection do
      get 'multi_stop'
      get 'multi_reboot'
      get 'remove_failed'
      get 'export_events'
      post 'filter'
    end
    member do
      get 'key'
      post 'stop'
      post 'reboot'
    end
    resources :instance_parameters
  end

  resources :image_imports

  resources :hardware_profiles do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
    post :matching_provider_hardware_profiles, :on => :collection
  end

  resources :providers do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection

    resources :provider_accounts do
      collection do
        delete 'multi_destroy'
        get 'set_selected_provider'
        post :filter
      end
    end
  end

  resources :provider_accounts, :only => :index

  resources :provider_types, :only => :index

  resources :users do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :user_groups do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get 'add_members'
      post 'add_members'
      delete 'remove_members'
      post 'filter_members'
    end
  end

  resources :logs do
    collection do
      post 'filter'
      get 'export_logs'
    end
  end

  resources :config_servers do
    member do
      get 'test'
    end
  end

  resources :roles do
    delete 'multi_destroy', :on => :collection
  end

  resources :pool_families do
    collection do
      delete 'multi_destroy'
      post 'add_provider_account'
    end
    member do
      get 'add_provider_accounts'
      post 'add_provider_accounts'
      post 'remove_provider_accounts'
    end
  end

  resources :frontend_realms do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :provider_realms do
    post :filter, :on => :collection
  end

  resources :realm_mappings do
    delete 'multi_destroy', :on => :collection
  end

  resources :catalogs do
    delete 'multi_destroy', :on => :collection
    post 'create'
    post :filter, :on => :collection
    resources :deployables do
      collection do
        delete 'multi_destroy'
        post :filter
      end
      member do
        get :definition
      end
    end
  end

  resources :catalog_entries

  resources :deployables do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get :definition
    end
  end

  resources :images do
    member do
      post 'rebuild_all'
      post 'push_all'
      get 'template'
    end
    collection do
      post 'edit_xml'
      post 'overview'
      delete 'multi_destroy'
      post 'import'
    end
    resources :target_images
    resources :provider_images
  end

  get 'api', :controller => 'api/entrypoint', :action => 'index'
  namespace :api do
    resources :images do
      resources :builds
    end
    resources :builds do
      resources :target_images
    end

    resources :target_images do
      resources :provider_images
    end

    resources :provider_images

    resources :hooks

    resources :environments do
      resources :images
    end
  end

  scope "/api", :as => 'api' do
    resources :providers, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :only => [:index, :create]
    end
    resources :provider_accounts, :only => [:index, :create, :show, :update, :destroy]
    resources :provider_types, :only => [:index, :show]
    resources :hardware_profiles, :only => [:index, :show, :destroy, :create]
    resources :pools, :only => [:index, :show, :create, :update, :destroy]
    resources :pool_families, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :controller => "pool_families_to_provider_accounts_associations", :only => [:index, :show, :update, :destroy]
    end
    resources :catalogs, :only => [:index, :show, :create, :update, :destroy]
    resources :provider_realms, :only => [:index, :show]
  end

  match     'dashboard', :to => 'dashboard', :as => 'dashboard'
  root      :to => "pools#index"

  match '/:controller(/:action(/:id))'
end

src/app/controllers/permissions_controller.rb
#
#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

class PermissionsController < ApplicationController
  before_filter :require_user

  def index
    set_permission_object(Privilege::PERM_VIEW)
    @roles = Role.find_all_by_scope(@permission_object.class.name)
    respond_to do |format|
      format.html
      format.json { render :json => @permission_object.as_json }
      format.js { render :partial => 'permissions' }
    end
  end

  def new
    set_permission_object
    @title = t'permissions.form.grant_access'
    @users = User.all
    @roles = Role.find_all_by_scope(@permission_object.class.name)
    if @permission_object == BasePermissionObject.general_permission_scope
      @return_text = t("permissions.new.global_role_grants")
      @summary_text =  t("permissions.new.choose_global_role")
    else
      @return_text =  "#{@permission_object.name} " + @permission_object.class.model_name.human
      @summary_text = t('permissions.new.choose_roles') + " " + @permission_object.class.model_name.human
    end
    load_headers
    load_entities
    respond_to do |format|
      format.html
      format.js { render :partial => 'new' }
    end
  end

  def create
    set_permission_object
    added=[]
    not_added=[]
    params[:entity_role_selected].each do |entity_role|
      entity_id,role_id = entity_role.split(",")
      unless role_id.nil?
        permission = Permission.new(:entity_id => entity_id,
                                    :role_id => role_id,
                                    :permission_object => @permission_object)
        if permission.save
          added << t('permissions.flash.fragment.user_and_role', :user => permission.entity.name,
                      :role => t(permission.role.name, :scope=> :role_defs, :default => permission.role.name))
        else
          not_added << t('permissions.flash.fragment.user_and_role', :user => permission.entity.name,
                          :role => t(permission.role.name, :scope=> :role_defs, :default => permission.role.name) )
        end
      end
    end
    unless added.empty?
      flash[:notice] = t('permissions.flash.notice.added', :list => added.to_sentence)
    end
    unless not_added.empty?
      flash[:error] = t('permissions.flash.error.not_added', :list => not_added.to_sentence)
    end
    if added.empty? and not_added.empty?
      flash[:error] = t "permissions.flash.error.no_users_selected"
    end
    respond_to do |format|
      format.html { redirect_to @return_path }
      format.js { render :partial => 'index',
                    :permission_object_type => @permission_object.class.name,
                    :permission_object_id => @permission_object.id }
    end
  end

  def multi_update
    set_permission_object
    modified=[]
    not_modified=[]
    params[:permission_role_selected].each do |permission_role|
      permission_id,role_id = permission_role.split(",")
      unless role_id.nil?
        permission = Permission.find(permission_id)
        role = Role.find(role_id)
        old_role = permission.role
        unless permission.role == role
          permission.role = role
          if permission.save
            modified << t('permissions.flash.fragment.user_and_role_change', :user => permission.entity.name,
                            :old_role => t(old_role.name, :scope=> :role_defs, :default => old_role.name),
                            :role => t(permission.role.name, :scope=> :role_defs, :default => permission.role.name))
          else
            not_modified << t('permissions.flash.fragment.user_and_role_change', :user => permission.entity.name,
                            :old_role => t(old_role.name, :scope=> :role_defs, :default => old_role.name) ,
                            :role => t(permission.role.name, :scope=> :role_defs, :default => permission.role.name))
          end
        end
      end
    end
    unless modified.empty?
      flash[:notice] = t('permissions.flash.notice.modified', :list => modified.to_sentence)
    end
    unless not_modified.empty?
      flash[:error] = t('permissions.flash.error.not_add', :list => not_modified.to_sentence)
    end
    if modified.empty? and not_modified.empty?
      flash[:notice] = t("permissions.flash.notice.no_change")
    end
    respond_to do |format|
      format.html { redirect_to @return_path }
      format.js { render :partial => 'index',
                    :permission_object_type => @permission_object.class.name,
                    :permission_object_id => @permission_object.id }
    end
  end

  def multi_destroy
    set_permission_object
    deleted=[]
    not_deleted=[]

    Permission.find(params[:permission_selected]).each do |p|
      if check_privilege(Privilege::PERM_SET, p.permission_object) && p.destroy
        deleted << t('permissions.flash.fragment.user_and_role', :user => p.entity.name,
                      :role => t(p.role.name, :scope=> :role_defs, :default => p.role.name))
      else
        not_deleted << t('permissions.flash.fragment.user_and_role', :user => p.entity.name,
                      :role => t(p.role.name, :scope=> :role_defs, :default => p.role.name))
      end
    end

    unless deleted.empty?
      flash[:notice] = t('permissions.flash.notice.deleted', :list => deleted.to_sentence)
    end
    unless not_deleted.empty?
      flash[:error] = t('permissions.flash.error.not_deleted', :list => not_deleted.to_sentence)
    end
    respond_to do |format|
      format.html { redirect_to @return_path }
        format.js { render :partial => 'index',
                    :permission_object_type => @permission_object.class.name,
                    :permission_object_id => @permission_object.id }
        format.json { render :json => @permission, :status => :created }
    end

  end
  def destroy
    if request.post?
      p =Permission.find(params[:permission][:id])
      require_privilege(Privilege::PERM_SET, p.permission_object)
      p.destroy
    end
    redirect_to :action => "list",
                :permission_object_type => p.permission_object_type,
                :permission_object_id => p.permission_object_id
  end

  def filter
    redirect_to_original({"permissions_preset_filter" => params[:permissions_preset_filter], "permissions_search" => params[:permissions_search]})
  end

  def filter_entities
    redirect_to_original({"entities_preset_filter" => params[:entities_preset_filter], "entities_search" => params[:entities_search]})
  end

  def profile_filter
    redirect_to_original({"profile_permissions_preset_filter" =>
                             params[:profile_permissions_preset_filter],
                          "profile_permissions_search" =>
                             (params[:profile_permissions_preset_filter].empty? ?
                              nil : params[:profile_permissions_search])})
  end

  private

  def load_entities
    sort_order = params[:sort_by].nil? ? "name" : params[:sort_by]
    @entities = paginate_collection(Entity.
      order(sort_column(Entity, sort_order)).
      apply_filters(:preset_filter_id => params[:entities_preset_filter],
                    :search_filter => params[:entities_search]),
                                    params[:page])
  end

  def load_headers
    @header = [
      { :name => '', :sortable => false },
      { :name => t('permissions.name') },
      { :name => t('role'), :sortable => false }
    ]
  end

  def set_permission_object (required_role=Privilege::PERM_SET)
    obj_type = params[:permission_object_type]
    id = params[:permission_object_id]
    @return_path = params[:return_path]
    @path_prefix = params[:path_prefix]
    @polymorphic_path_extras = params[:polymorphic_path_extras]
    @use_tabs = params[:use_tabs]
    unless obj_type or id
      @permission_object = BasePermissionObject.general_permission_scope
    end
    if obj_type && id
      if klass = ActiveRecord::Base.send(:subclasses).find{|c| c.name == obj_type}
        @permission_object = klass.find(id)
      else
        raise RuntimeError, "invalid permission object type #{obj_type}"
      end
    end
    raise RuntimeError, "invalid permission object" if @permission_object.nil?
    unless @return_path
      if @permission_object == BasePermissionObject.general_permission_scope
        @return_path = permissions_path(:return_from_permission_change => true)
        set_admin_users_tabs 'permissions'
      else
        @return_path = send("#{@path_prefix}polymorphic_path",
                            @permission_object.respond_to?(
                              :to_polymorphic_path_param) ?
                            @permission_object.to_polymorphic_path_param(
                              @polymorphic_path_extras) :
                            @permission_object,
                            @use_tabs == "yes" ? {:details_tab => :permissions,
                              :only_tab => true,
                              :return_from_permission_change => true} :
                             {:return_from_permission_change => true})
      end
    end
    require_privilege(required_role, @permission_object)
    set_permissions_header
  end
end

src/app/views/permissions/_form.html.haml
- content_for :entities_filter_controls do
  %li
    = label_tag :entities_preset_filter, t('filter_table.viewing')
    = select_tag(:entities_preset_filter, preset_filters_options_for_select(Entity::PRESET_FILTERS_OPTIONS, params[:entities_preset_filter]), :include_blank => t("permissions.preset_filters.all_entities"), :disabled => false)
    = hidden_field_tag :current_path, request.fullpath
    = restful_submit_tag t("filter_table.apply_filters"), "filter", filter_entities_permissions_path, 'POST', :class => 'button', :id => 'apply_entities_preset_filter'
    %span.label.badge.dark= @entities.count
  %li.table-search-filter
    = text_field_tag :entities_search, params[:entities_search], :placeholder => t("filter_table.search")
    = restful_submit_tag "", "search", filter_entities_permissions_path, 'POST', :class => 'button', :id => 'apply_entities_search'

  :javascript
    $(document).ready(function(){
      $("#apply_entities_preset_filter").hide();
      $("#entities_preset_filter").change(function() {
        $("#apply_entities_preset_filter").click();
      });
      Conductor.clickOnEnterKeypress($('#entities_search'), $('#apply_entities_search'));
    });

- content_for :form_footer do
  = hidden_field_tag :permission_object_type, @permission_object.class.name
  = hidden_field_tag :permission_object_id, @permission_object.id
  = hidden_field_tag :path_prefix, @path_prefix
  = hidden_field_tag :use_tabs, @use_tabs
  = restful_submit_tag t('permissions.form.grant_access'), "create", permissions_path, 'POST', :id => 'save_button', :class => 'button primary'
  = link_to t('cancel'), @return_path, :class => 'button danger'
= filter_table(@header, @entities,
               :filter_controls => :entities_filter_controls) do |entity|
  %tr{:class => cycle('nostripe','stripe')}
    %td
      -# - selected = params[:select] == 'all'
      -#  = check_box_tag "entity_selected[]", entity.id, selected, :id => "entity_checkbox_#{entity.id}"
    %td= link_to entity.name, ((entity.entity_target_type == "User") ? user_path(entity.user) : user_group_path(entity.user_group))
    %td= select_tag "entity_role_selected[]", options_for_select([['', "#{entity.id},"]] + @roles.map {|r| [t(r.name, :scope=> :role_defs, :default => r.name), "#{entity.id},#{r.id}" ] }, :disabled => @permission_object.permissions.where(:entity_id=>entity.id).collect {|p| "#{entity.id},#{p.role.id}"}), :id => "entity_role_selected_#{entity.id}"

src/app/views/permissions/_list.html.haml
= render :partial => 'permissions'

src/app/views/permissions/_objects.html.haml
- content_for :permissions_form_header do
  %span{:id => ("tab-container-1-nav" unless @inline)}
    - if @show_inherited
      %li= link_to t('permissions.direct_access'), params.merge(:show_inherited => false, :page => 1), { :class => 'button primary', :id => 'direct_permission_button'}
    - else
      %li= link_to t('permissions.inherited_access'), params.merge(:show_inherited => true, :page => 1), { :class => 'button primary', :id => 'inherited_permission_button'}

  - if not(@show_inherited) && check_privilege(Privilege::PERM_SET)
    %li= restful_submit_tag t('permissions.revoke_access'), "destroy", multi_destroy_permissions_path, 'DELETE', :id => 'revoke_button', :class => 'button danger'
    %li= restful_submit_tag t('edit'), "multi_update", multi_update_permissions_path, 'POST', :id => 'perm_edit_button', :class => 'hidden'
    = hidden_field_tag :entity_id, @entity.id

    = hidden_field_tag :path_prefix, @path_prefix
    = hidden_field_tag :return_path, url_for(@entity.entity_target)
    = hidden_field_tag :use_tabs, @use_tabs ? @use_tabs : (@tabs ? 'yes' : 'no')

- content_for :permissions_filter_controls do
  %li
    = label_tag :profile_permissions_preset_filter, t('filter_table.viewing')
    = select_tag(:profile_permissions_preset_filter, preset_filters_options_for_select(Permission::PROFILE_PRESET_FILTERS_OPTIONS, params[:profile_permissions_preset_filter]), :include_blank => t("permissions.preset_filters.all_permissions"), :disabled => false)
    = hidden_field_tag :current_path, request.fullpath
    = restful_submit_tag t("filter_table.apply_filters"), "profile_filter", profile_filter_permissions_path, 'POST', :class => 'button', :id => 'apply_profile_permissions_preset_filter'
    %span.label.badge.dark= @permissions.count
  %li.table-search-filter
    - disable_search = params[:profile_permissions_preset_filter].nil? || params[:profile_permissions_preset_filter].empty?
    = text_field_tag :profile_permissions_search, (disable_search ? nil : params[:profile_permissions_search]), :placeholder => t("filter_table.search"), :disabled => disable_search
    = restful_submit_tag "", "search", profile_filter_permissions_path, 'POST', :class => 'button', :id => 'apply_profile_permissions_search'

  :javascript
    $(document).ready(function(){
      $("#apply_profile_permissions_preset_filter").hide();
      $("#profile_permissions_preset_filter").change(function() {
        $("#apply_profile_permissions_preset_filter").click();
      });
      Conductor.clickOnEnterKeypress($('#profile_permissions_search'), $('#apply_profile_permissions_search'));
    });

= filter_table(@permission_list_header,
               @permissions,
               :form_header => :permissions_form_header,
               :filter_controls => :permissions_filter_controls) do |permission|
  %tr{:class => cycle('nostripe','stripe')}
    - if not(@show_inherited)
      %td{:class => 'checkbox'}
        - if check_privilege(Privilege::PERM_SET)
          - selected = params[:select] == 'all'
          = check_box_tag "permission_selected[]", permission.id, selected, :id => "permission_checkbox_#{permission.id}"
    - if permission.permission_object.class == BasePermissionObject
      %td= t'permissions.global'
      %td
    - else
      %td= t("activerecord.models.#{permission.permission_object_type.underscore}")
      %td= link_to permission.permission_object.name, permission.permission_object
    - if not(@show_inherited) && check_privilege(Privilege::PERM_SET)
      %td= select_tag "permission_role_selected[]", options_for_select(@roles[permission.permission_object_type].map {|r| [ t(r.name, :scope=> :role_defs, :default => r.name), "#{permission.id},#{r.id}" ] }, :selected => "#{permission.id},#{permission.role.id}", :disabled => @entity.permissions.where(["entity_id = ? and role_id != ?", permission.entity_id, permission.role_id]).collect {|p| "#{permission.id},#{p.role.id}"}), :id => "permission_role_selected_#{permission.id}"
      :javascript
        $("#permission_role_selected_#{permission.id}").change(function () { $("#perm_edit_button").click(); } );

    -else
      %td= t(permission.role.name, :scope=> :role_defs, :default => permission.role.name)
    - if @show_inherited
      - if permission.permission.permission_object.class == BasePermissionObject
        %td= t'permissions.global'
      - else
        %td= link_to permission.permission.permission_object.name, permission.permission.permission_object

src/app/views/permissions/_permissions.haml
- content_for :form_header do
  - if check_privilege(Privilege::PERM_SET)
    %li
      = link_to "Grant Access", new_permission_path(:permission_object_type => @permission_object.class.name, :permission_object_id => @permission_object.id), { :class => 'button primary', :id => 'new_permission_button'}
      = restful_submit_tag "Revoke Access", "destroy", multi_destroy_permissions_path, 'DELETE', :id => 'delete_button', :class => 'button danger'
      = restful_submit_tag "Edit", "multi_update", multi_update_permissions_path, 'POST', :id => 'edit_button', :class => 'hidden'
    .corner &nbsp;
    = hidden_field_tag :permission_object_type, @permission_object.class.name
    = hidden_field_tag :permission_object_id, @permission_object.id

= filter_table(@permission_list_header, @permission_object.permissions) do |permission|
  %tr{:class => cycle('nostripe','stripe')}
    %td
      - if check_privilege(Privilege::PERM_SET)
        - selected = params[:select] == 'all'
        = check_box_tag "permission_selected[]", permission.id, selected, :id => "permission_checkbox_#{permission.id}"
    %td= link_to "#{permission.user.first_name} #{permission.user.last_name}", user_path(permission.user)
    - if check_privilege(Privilege::PERM_SET)
      %td= select_tag "permission_role_selected[]", options_for_select(@roles.map {|r| [ r.name, "#{permission.id},#{r.id}" ] }, :selected => "#{permission.id},#{permission.role.id}", :disabled => @permission_object.permissions.where(["user_id = ? and role_id != ?", permission.user_id, permission.role_id]).collect {|p| "#{permission.id},#{p.role.id}"}), :id => "permission_role_selected_#{permission.id}"
      :javascript
        $("#permission_role_selected_#{permission.id}").change(function () { $("#edit_button").click(); } );

    -else
      %td= permission.role.name

src/app/views/permissions/_permissions.html.haml
- has_admin_perms = check_privilege(Privilege::PERM_SET)
- prevent_admin_deletion = has_admin_perms && !(@show_inherited || @show_global) && (@permission_object == BasePermissionObject.general_permission_scope) && (BasePermissionObject.global_admin_permission_count == 1)
- content_for :permissions_form_header do
  - if not(@show_inherited or @show_global) && check_privilege(Privilege::PERM_SET)
    %li= link_to t('permissions.form.grant_access'), new_permission_path(:permission_object_type => @permission_object.class.name, :permission_object_id => @permission_object.id, :path_prefix => @path_prefix, :use_tabs => @use_tabs ? @use_tabs : (@tabs ? 'yes' : 'no')), { :class => 'button primary', :id => 'new_permission_button'}
    %li= restful_submit_tag t('permissions.revoke_access'), "destroy", multi_destroy_permissions_path, 'DELETE', :id => 'revoke_button', :class => 'button danger'
    %li= restful_submit_tag t('edit'), "multi_update", multi_update_permissions_path, 'POST', :id => 'perm_edit_button', :class => 'hidden'
    = hidden_field_tag :permission_object_type, @permission_object.class.name
    = hidden_field_tag :permission_object_id, @permission_object.id

    - if @polymorphic_path_extras.present?
      - @polymorphic_path_extras.each do |key, value|
        = hidden_field_tag("polymorphic_path_extras[#{key}]", value)

    = hidden_field_tag :path_prefix, @path_prefix
    = hidden_field_tag :use_tabs, @use_tabs ? @use_tabs : (@tabs ? 'yes' : 'no')
  %span{:id => ("tab-container-1-nav" unless @inline)}
    - unless @permission_object == BasePermissionObject.general_permission_scope
      - if @show_inherited
        %li= link_to t('permissions.direct_access'), params.merge(:show_inherited => false, :show_global => false, :page => 1), { :class => 'button', :id => 'direct_permission_button'}
        %li= link_to t('permissions.global_access'), params.merge(:show_inherited => false, :show_global => true, :page => 1), { :class => 'button', :id => 'global_permission_button'}
      - elsif @show_global
        %li= link_to t('permissions.direct_access'), params.merge(:show_inherited => false, :show_global => false, :page => 1), { :class => 'button', :id => 'direct_permission_button'}
        %li= link_to t('permissions.inherited_access'), params.merge(:show_inherited => true, :show_global => false, :page => 1), { :class => 'button', :id => 'inherited_permission_button'}
      - else
        %li= link_to t('permissions.inherited_access'), params.merge(:show_inherited => true, :show_global => false, :page => 1), { :class => 'button', :id => 'inherited_permission_button'}
        %li= link_to t('permissions.global_access'), params.merge(:show_inherited => false, :show_global => true, :page => 1), { :class => 'button', :id => 'global_permission_button'}

- content_for :permissions_filter_controls do
  %li
    = label_tag :permissions_preset_filter, t('filter_table.viewing')
    = select_tag(:permissions_preset_filter, preset_filters_options_for_select(Permission::PRESET_FILTERS_OPTIONS, params[:permissions_preset_filter]), :include_blank => t("permissions.preset_filters.all_permissions"), :disabled => false)
    = hidden_field_tag :current_path, request.fullpath
    = restful_submit_tag t("filter_table.apply_filters"), "filter", filter_permissions_path, 'POST', :class => 'button', :id => 'apply_permissions_preset_filter'
    %span.label.badge.dark= @permissions.count
  %li.table-search-filter
    = text_field_tag :permissions_search, params[:permissions_search], :placeholder => t("filter_table.search")
    = restful_submit_tag "", "search", filter_permissions_path, 'POST', :class => 'button', :id => 'apply_permissions_search'

  :javascript
    $(document).ready(function(){
      $("#apply_permissions_preset_filter").hide();
      $("#permissions_preset_filter").change(function() {
        $("#apply_permissions_preset_filter").click();
      });
      Conductor.clickOnEnterKeypress($('#permissions_search'), $('#apply_permissions_search'));
    });

= filter_table(@permission_list_header,
               @permissions,
               :form_header => :permissions_form_header,
               :filter_controls => :permissions_filter_controls) do |permission|
  %tr{:class => cycle('nostripe','stripe')}
    - if not(@show_inherited or @show_global)
      %td{:class => 'checkbox'}
        - if has_admin_perms && !(prevent_admin_deletion && BasePermissionObject.is_global_admin_perm(permission))
          - selected = params[:select] == 'all'
          = check_box_tag "permission_selected[]", permission.id, selected, :id => "permission_checkbox_#{permission.id}"
    %td= link_to permission.entity.name, ((permission.entity.entity_target_type == "User") ? user_path(permission.entity.user) : user_group_path(permission.entity.user_group))
    - if !(@show_inherited || @show_global) && has_admin_perms && !(prevent_admin_deletion && BasePermissionObject.is_global_admin_perm(permission))
      %td= select_tag "permission_role_selected[]", options_for_select(@roles.map {|r| [ t(r.name, :scope=> :role_defs, :default => r.name), "#{permission.id},#{r.id}" ] }, :selected => "#{permission.id},#{permission.role.id}", :disabled => @permission_object.permissions.where(["entity_id = ? and role_id != ?", permission.entity_id, permission.role_id]).collect {|p| "#{permission.id},#{p.role.id}"}), :id => "permission_role_selected_#{permission.id}"
      :javascript
        $("#permission_role_selected_#{permission.id}").change(function () { $("#perm_edit_button").click(); } );

    -else
      %td= t(permission.role.name, :scope=> :role_defs, :default => permission.role.name)
    - if @show_inherited
      %td= permission.permission.permission_object.name

src/app/views/permissions/index.haml
= render :partial => 'permissions'

src/app/views/permissions/new.haml
= render :partial => 'new'