src/config/routes.rb
Conductor::Application.routes.draw do

  resource :user_sessions
  match 'login',       :to => 'user_sessions#new',     :as => 'login'
  match 'logout',      :to => 'user_sessions#destroy', :as => 'logout'
  match 'register',    :to => 'users#new',             :as => 'register'

  resource  'account', :to => 'users'

  resources :password_resets, :only => [:create, :edit, :update]
  resources :username_recoveries, :only => [:create]

  resources :templates
  resources :permissions do
    collection do
      get :list
      delete :multi_destroy
      post :multi_update
      post :filter
      post :filter_entities
      post :profile_filter
    end
  end

  resources :settings do
    collection do
      get :self_service
    end
  end
  resources :pools do
    delete :multi_destroy, :on => :collection
    post :filter, :on => :collection

    resource :provider_selection, :only => [:show] do
      resources :provider_priority_groups, :except => [:show]

      match ':strategy_name/toggle', :to => 'provider_selections#toggle_strategy', :as => 'toggle_strategy'
      match ':strategy_name/edit', :to => 'provider_selections#edit_strategy', :as => 'edit_strategy'
      match ':strategy_name/save_strategy_options', :to => 'provider_selections#save_strategy_options', :as => 'save_strategy_options'
    end
  end

  resources :deployments do
    collection do
      get 'multi_stop'
      delete :multi_destroy
      get 'launch_new'
      post 'launch_time_params'
      get 'launch_time_params'
      post 'overview'
      get 'check_name'
      get 'launch_from_catalog'
      post 'filter'
    end
    resources :instances
  end

  resources :instances do
    collection do
      get 'multi_stop'
      get 'multi_reboot'
      get 'remove_failed'
      get 'export_events'
      post 'filter'
    end
    member do
      get 'key'
      post 'stop'
      post 'reboot'
    end
    resources :instance_parameters
  end

  resources :image_imports

  resources :hardware_profiles do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
    post :matching_provider_hardware_profiles, :on => :collection
  end

  resources :providers do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection

    resources :provider_accounts do
      collection do
        delete 'multi_destroy'
        get 'set_selected_provider'
        post :filter
      end
    end
  end

  resources :provider_accounts, :only => :index

  resources :provider_types, :only => :index

  resources :users do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :user_groups do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get 'add_members'
      post 'add_members'
      delete 'remove_members'
      post 'filter_members'
    end
  end

  resources :logs do
    collection do
      post 'filter'
      get 'export_logs'
    end
  end

  resources :config_servers do
    member do
      get 'test'
    end
  end

  resources :roles do
    delete 'multi_destroy', :on => :collection
  end

  resources :pool_families do
    collection do
      delete 'multi_destroy'
      post 'add_provider_account'
    end
    member do
      get 'add_provider_accounts'
      post 'add_provider_accounts'
      post 'remove_provider_accounts'
    end
  end

  resources :frontend_realms do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :provider_realms do
    post :filter, :on => :collection
  end

  resources :realm_mappings do
    delete 'multi_destroy', :on => :collection
  end

  resources :catalogs do
    delete 'multi_destroy', :on => :collection
    post 'create'
    post :filter, :on => :collection
    resources :deployables do
      collection do
        delete 'multi_destroy'
        post :filter
      end
      member do
        get :definition
      end
    end
  end

  resources :catalog_entries

  resources :deployables do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get :definition
    end
  end

  resources :images do
    member do
      post 'rebuild_all'
      post 'push_all'
      get 'template'
    end
    collection do
      post 'edit_xml'
      post 'overview'
      delete 'multi_destroy'
      post 'import'
    end
    resources :target_images
    resources :provider_images
  end

  get 'api', :controller => 'api/entrypoint', :action => 'index'
  namespace :api do
    resources :images do
      resources :builds
    end
    resources :builds do
      resources :target_images
    end

    resources :target_images do
      resources :provider_images
    end

    resources :provider_images

    resources :hooks

    resources :environments do
      resources :images
    end
  end

  scope "/api", :as => 'api' do
    resources :providers, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :only => [:index, :create]
    end
    resources :provider_accounts, :only => [:index, :create, :show, :update, :destroy]
    resources :provider_types, :only => [:index, :show]
    resources :hardware_profiles, :only => [:index, :show, :destroy, :create]
    resources :pools, :only => [:index, :show, :create, :update, :destroy]
    resources :pool_families, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :controller => "pool_families_to_provider_accounts_associations", :only => [:index, :show, :update, :destroy]
    end
    resources :catalogs, :only => [:index, :show, :create, :update, :destroy]
    resources :provider_realms, :only => [:index, :show]
  end

  match     'dashboard', :to => 'dashboard', :as => 'dashboard'
  root      :to => "pools#index"

  match '/:controller(/:action(/:id))'
end

src/app/models/pool_family.rb
#
#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# == Schema Information
# Schema version: 20110603204130
#
# Table name: pool_families
#
#  id           :integer         not null, primary key
#  name         :string(255)     not null
#  description  :string(255)
#  lock_version :integer         default(0)
#  created_at   :datetime
#  updated_at   :datetime
#  quota_id     :integer
#

# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class PoolFamily < ActiveRecord::Base

  include PermissionedObject
  include ActionView::Helpers::NumberHelper

  DEFAULT_POOL_FAMILY_KEY = "default_pool_family"

  before_destroy :check_name!
  before_destroy :check_pools!
  before_destroy :check_images!

  has_many :pools,  :dependent => :destroy
  belongs_to :quota, :autosave => true, :dependent => :destroy
  has_and_belongs_to_many :provider_accounts, :uniq => true, :order => "provider_accounts.priority asc"
  has_many :permissions, :as => :permission_object, :dependent => :destroy
  has_many :derived_permissions, :as => :permission_object, :dependent => :destroy,
           :include => [:role],
           :order => "derived_permissions.id ASC"
             has_many :catalogs
  has_many :deployables
  has_many :instances
  has_many :deployments
  has_many :base_images, :class_name => "Tim::BaseImage"
  has_many :templates, :class_name => "Tim::Template"

  accepts_nested_attributes_for :quota

  after_update :fix_iwhd_environment_tags

  validates :name, :presence => true,
                   :uniqueness => true,
                   :length => { :within => 1..100 },
                   :format => { :with => /^[\w -]*$/n }
  validates :quota, :presence => true

  def self.default
    MetadataObject.lookup(DEFAULT_POOL_FAMILY_KEY)
  end

  def set_as_default
    MetadataObject.set(DEFAULT_POOL_FAMILY_KEY, self)
  end

  def self.additional_privilege_target_types
    [Pool, Quota, Tim::BaseImage, Tim::Template]
  end

  def derived_subtree(role = nil)
    subtree = super(role)
    subtree += pools if (role.nil? or role.privilege_target_match(Pool))
    subtree += deployments if (role.nil? or role.privilege_target_match(Deployment))
    subtree += instances if (role.nil? or role.privilege_target_match(Instance))
    subtree += catalogs if (role.nil? or role.privilege_target_match(Deployable))
    subtree += deployables if (role.nil? or role.privilege_target_match(Deployable))
    subtree += base_images if (role.nil? or role.privilege_target_match(Tim::BaseImage))
    subtree += templates if (role.nil? or role.privilege_target_match(Tim::Template))
    subtree
  end

  def check_pools!
    cant_destroy = pools.find_all {|p| !p.destroyable?}
    if cant_destroy.empty?
      true
    else
      raise Aeolus::Conductor::Base::NotDestroyable,
        I18n.t('pool_families.errors.not_destroyable_pools',
               :list => cant_destroy.map {|p| p.name}.join(', '))
    end
  end

  def check_name!
    if self == PoolFamily.default
      raise Aeolus::Conductor::Base::NotDestroyable,
        I18n.t('pool_families.errors.default_pool_family_not_deleted')
    else
      true
    end
  end

  def check_images!
    if base_images.empty?
      true
    else
      raise Aeolus::Conductor::Base::NotDestroyable,
        I18n.t('pool_families.errors.associated_images',
               :list => base_images.map {|i| i.name}.join(', '))
    end
  end

  def all_providers_disabled?
    !provider_accounts.empty? and !provider_accounts.any? {|acc| acc.provider.enabled?}
  end

  def provider_accounts_by_priority
    provider_accounts.sort {|a,b|
      if a.priority.nil? and b.priority.nil?
        0
      elsif a.priority.nil?
        1
      elsif b.priority.nil?
        -1
      else
        a.priority <=> b.priority
      end
    }
  end

  def statistics
    max = quota.maximum_running_instances
    total = quota.running_instances
    avail = max - total unless max.nil?
    # Don't make repeat calls to the pools association
    cached_pools = pools
    statistics = {
      :deployments => cached_pools.collect{|p| p.deployments.count}.sum,
      :total_instances => cached_pools.collect{|p| p.instances.not_stopped.count}.sum,
      :instances_pending => cached_pools.collect{|p| p.instances.pending.count}.sum,
      :instances_failed => cached_pools.collect{|p| p.instances.failed.count}.sum,
      :used_quota => total,
      :quota_percent => number_to_percentage(quota.percentage_used,
                                             :precision => 0),
      :available_quota => avail,
    }
  end
  def build_targets
    targets = []
    ProviderAccount.enabled.group_by_type(self).each do |driver, group|
      targets << driver if group[:included]
    end
    targets
  end
end

src/app/controllers/admin/pool_families_controller.rb
class Admin::PoolFamiliesController < ApplicationController
  before_filter :require_user
  before_filter :set_params_and_header, :only => [:index, :show]
  before_filter :load_pool_families, :only =>[:show]
  before_filter :load_tab_captions_and_details_tab, :only => [:show]

  def index
    @search_term = params[:q]
    if @search_term.blank?
      load_pool_families
      return
    end

    search = PoolFamily.search() do
      keywords(params[:q])
    end
    @pool_families = search.results
  end

  def new
    @pool_family = PoolFamily.new(:quota => Quota.new)
  end

  def create
    @pool_family = PoolFamily.new(params[:pool_family])
    unless @pool_family.save
      flash.now[:warning] = "Pool family's creation failed."
      render :new and return
    else
      @pool_family.assign_owner_roles(current_user)
      flash[:notice] = "Pool family was added."
      redirect_to admin_pool_families_path
    end
  end

  def edit
    @pool_family = PoolFamily.find(params[:id])
    @pool_family.quota ||= Quota.new
  end

  def update
    @pool_family = PoolFamily.find(params[:id])
    unless @pool_family.update_attributes(params[:pool_family])
      flash[:error] = "Pool Family wasn't updated!"
      render :action => 'edit' and return
    else
      flash[:notice] = "Pool Family was updated!"
      redirect_to admin_pool_families_path
    end
  end

  def show
    @pool_family = PoolFamily.find(params[:id])
    @url_params = params.clone

    respond_to do |format|
      format.js do
        if @url_params.delete :details_pane
          render :partial => 'layouts/details_pane' and return
        end
        render :partial => @details_tab and return
      end
      format.html { render :show }
    end
  end

  def add_provider_account
    @pool_family = PoolFamily.find(params[:id])
    @provider_account = ProviderAccount.find(params[:provider_account_id])

    @pool_family.provider_accounts << @provider_account
    flash[:notice] = "Provider Account has been added"
    redirect_to admin_pool_family_path(@pool_family, :details_tab => 'provider_accounts')
  end

  def multi_destroy
    deleted = []
    not_deleted = []
    PoolFamily.find(params[:pool_family_selected]).each do |pool_family|
      if pool_family.destroy
        deleted << pool_family.name
      else
        not_deleted << pool_family.name
      end
    end
    if deleted.size > 0
      flash[:notice] = t 'pool_families.index.deleted', :list => deleted.join(', ')
    end
    if not_deleted.size > 0
      flash[:error] = t 'pool_families.index.not_deleted', :list => not_deleted.join(', ')
    end
    redirect_to admin_pool_families_path
  end

  def multi_destroy_provider_accounts
    @pool_family = PoolFamily.find(params[:pool_family_id])

    ProviderAccount.find(params[:provider_account_selected]).each do |provider_account|
      @pool_family.provider_accounts.delete provider_account
    end

    redirect_to admin_pool_family_path(@pool_family, :details_tab => 'provider_accounts')
  end

  protected

  def load_tab_captions_and_details_tab
    @tab_captions = ['Properties', 'History', 'Permissions', 'Provider Accounts', 'Pools']
    @details_tab = params[:details_tab].blank? ? 'properties' : params[:details_tab]
    @provider_accounts_header = [{ :name => "Provider Account", :sort_attr => :name}]
  end

  def set_params_and_header
    @url_params = params.clone
    @header = [{ :name => "Name", :sort_attr => :name},
               { :name => "Quota limit", :sort_attr => :name},
               { :name => "Quota currently in use", :sort_attr => :name},
    ]
  end

  def load_pool_families
    @pool_families = PoolFamily.paginate(:all,
                                         :page => params[:page] || 1,
                                         :order => ( params[:order_field] || 'name' ) + ' ' + (params[:order_dir] || 'asc')
                                        )
  end
end

src/app/views/pool_families/_add_provider_accounts_form.html.haml
- content_for :form_footer do
  = link_to t('cancel'), pool_family_path(@pool_family, :details_tab => 'provider_accounts'), :class => 'button danger'
  = restful_submit_tag t('provider_accounts.add_provider_account'), "create", add_provider_accounts_pool_family_path(@pool_family), 'POST', :id => 'save_button', :class => 'button'
= filter_table(provider_accounts_header(:without_alert => true), @provider_accounts) do |account|
  %tr{:class => cycle('nostripe','stripe')}
    %td{:class => 'checkbox'}
      - if check_privilege(Privilege::MODIFY)
        - selected = params[:select] == 'all'
        = check_box_tag "accounts_selected[]", account.id, selected, :id => "account_checkbox_#{account.id}"
    %td= link_to account.name, provider_provider_account_path(account.provider, account)
    %td= account.credentials_hash['username']
    %td= account.provider.name
    %td= account.provider.provider_type.name
    %td= account.priority
    %td{:class => 'center'}= number_to_percentage account.quota.percentage_used, :precision => 0
    %td{:class => 'center'}= account.quota.maximum_running_instances or 'unlimited'

src/app/views/pool_families/_detail.xml.haml
!!! XML
%pool_family{:id => pool_family.id, :href => api_pool_family_url(pool_family)}
  %name= pool_family.name
  -if pool_family.quota.maximum_running_instances
    %quota{ :maximum_running_instances => pool_family.quota.maximum_running_instances}
  -else
    %quota{ :maximum_running_instances => t('pools.form.unlimited')}
  %pools
    - pool_family.pools.each do |pool|
      %pool{:id => pool.id, :href => api_pool_url(pool.id)}
  %provider_accounts
    - pool_family.provider_accounts.each do |pa|
      %provider_account{:id => pa.id, :href => api_provider_account_url(pa.id)}
  %images
    - pool_family.images.each do |image|
      %image{:id => image.id, :href => api_image_url(image.id)}

src/app/views/pool_families/_form.html.haml
= form.input :name
= form.fields_for :quota do |quota_form|
  = quota_form.input :maximum_running_instances, :as => :numeric_input_with_unlimited_check_box

src/app/views/pool_families/_images.html.haml
- content_for :form_header do
  - if check_privilege(Privilege::CREATE, Tim::BaseImage, @pool_family)
    / FIXME: why image new/import is displayed only if a pool exists
    / also there should be some error message in such case
    - if @pool_family.pools.any?
      %li= link_to t('tim.base_images.import.import_image'), main_app.new_image_import_path('image_import[pool_family_id]' => @pool_family.id), { :class => 'button primary', :id => 'import_image_button'}
      %li= link_to t('tim.base_images.index.new'), tim.new_base_image_path('base_image[pool_family_id]' => @pool_family.id), { :class => 'button primary', :id => 'import_image_button'}
  - if check_privilege(Privilege::MODIFY, Tim::BaseImage, @pool_family)
    %li= restful_submit_tag t("delete"), "destroy", multi_destroy_images_path, 'DELETE', :id => 'delete_button', :class => 'button danger'

= render :partial => "tim/base_images/list", :locals => {:image_row_partial => 'tim/base_images/image_row_for_environment'}

src/app/views/pool_families/_provider_accounts.html.haml
- content_for :form_header do
  - if check_privilege(Privilege::MODIFY)
    %li= link_to t('provider_accounts.add_provider_account'), add_provider_accounts_pool_family_path(@pool_family), { :class => 'button primary', :id => 'add_provider_accounts_button'}
    %li= restful_submit_tag t('delete'), "destroy", remove_provider_accounts_pool_family_path(@pool_family), 'POST', :id => 'remove_button', :class => 'button danger'

= filter_table(provider_accounts_header(:without_alert => true), @pool_family.provider_accounts) do |account|
  %tr{:class => cycle('nostripe','stripe')}
    %td{:class => 'checkbox'}
      - if check_privilege(Privilege::MODIFY)
        - selected = params[:select] == 'all'
        = check_box_tag "accounts_selected[]", account.id, selected, :id => "account_checkbox_#{account.id}"
    %td= link_to account.name, provider_provider_account_path(account.provider, account)
    %td= account.credentials_hash['username']
    %td= account.provider.name
    %td= account.provider.provider_type.name
    %td= account.priority
    %td{:class => 'center'}= number_to_percentage account.quota.percentage_used, :precision => 0
    %td{:class => 'center'}= account.quota.maximum_running_instances or 'unlimited'

src/app/views/pool_families/_section_header.haml
%header.page-header
  %h1{:class => controller.controller_name} Pool Families
  #obj_actions.button-group
    = link_to 'New Pool Family', new_pool_family_url, :class => 'button primary', :id => 'new_pool_family_button'
  .corner &nbsp;

src/app/views/pool_families/_section_header.html.haml
%header.page-header
  #obj_actions.button-group
    = link_to 'New Pool Family', new_pool_family_url, :class => 'button primary', :id => 'new_pool_family_button'
  %h1.pool_families Pool Families

src/app/views/pool_families/add_provider_accounts.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  #obj_actions.button-container
    .return_to
      = t'return_to'
      = link_to @pool_family.name, pool_family_path(@pool_family, :details_tab => 'provider_accounts'), :id => 'new_pool_button'
  %h1.pool_families= @pool_family.name

%section.content-section.pool_families
  %h3= t("pool_families.choose_provider_accounts")
  %header#tab-container-1
    %h2.settings= #t("settings.settings")
    %nav.faceted
  .content#tab
    = render :partial => 'add_provider_accounts_form'

src/app/views/pool_families/edit.html.haml
= render :partial => 'layouts/admin_nav'

%header.page-header
  .obj_actions
    .return_to
      = t("return_to")
      = link_to t("pool_families.new.environments"), pool_families_path
  %h1.pool_families= @title

%section.content-section.pool_family
  .content
    = conductor_form_for @pool_family do |f|
      = render :partial => "form", :locals => { :form => f }
      = f.button :form_buttons, :cancel => pool_families_path

src/app/views/pool_families/index.html.haml
= render :partial => 'layouts/admin_nav'
= #render :partial => 'list'
%section.admin-content-section.pool_families
  %header
    %h2.pools= t("pool_families.pool_families")
    .section-controls
      #obj_actions
        = link_to t("pool_families.index.new_pool_family"), new_pool_family_path, :class => 'button pill', :id => 'new_pool_family_button'

  .content
    - @pool_families.each do |pool_family|
      %table.pool_families
        %caption
          .caption_content
            %header
              %h2
                = link_to pool_family.name, pool_family
              .section-controls
                #obj_actions
                  = link_to t(:edit), edit_pool_family_path(pool_family), :class => 'rounded-link'
                  = link_to t("pools.new_pool"), new_pool_path, :class => 'rounded-link'
        - unless pool_family.pools.blank?
          %tr
            %th= t("pool_families.index.pool_name")
            %th= t("pool_families.index.deployments")
            %th= t("pool_families.index.total_instancies")
            %th= t("pool_families.index.pending_instances")
            %th= t("pool_families.index.failed_instances")
            %th= t("pool_families.index.quota_used")
            %th= t("pool_families.index.active_instances")
            %th= t("pool_families.index.available_instances")
            %th= t("pool_families.index.catalog")
            %th
          - pool_family.pools.each do |pool|
            %tr
              %td= link_to pool.name, pool
              %td= pool.deployments.count
              %td= pool.statistics[:total_instances]
              %td= pool.statistics[:instances_pending]
              %td= pool.statistics[:instances_failed]
              %td= pool.statistics[:quota_percent]
              %td= pool.statistics[:used_quota]
              %td= pool.statistics[:available_quota].nil? ? raw('&infin;') : pool.statistics[:available_quota]
              %td= link_to pool.catalogs.first.name, catalog_path(pool.catalogs.first) if pool.catalogs.any?
              %td= link_to t(:edit), edit_pool_path(pool), :class => 'rounded-link'

src/app/views/pool_families/new.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  .obj_actions
    .return_to
      = t("return_to")
      = link_to t("pool_families.new.environments"), pool_families_path
  %h1.pool_families= @title

%section.content-section.pool_family
  .content
    = conductor_form_for @pool_family do |f|
      = render :partial => "form", :locals => { :form => f }
      = f.button :form_buttons, :cancel => pool_families_path

src/app/views/pool_families/show.haml
= render :partial => 'layouts/admin_nav'
%header.admin-page-header
  %h1= @pool_family.name
  #obj_actions.button-container
    .button-group
      = link_to 'Edit', edit_pool_family_path(@pool_family), :class => 'button pill'
      = button_to 'Delete', pool_family_path(@pool_family), :method => :delete, :confirm => "Are you sure you want to delete?", :class => "button pill danger", :id => 'delete_pool_family_button'

%section.admin-content-section.pool_family
  .content
    = render :partial => 'properties'
    = render :partial => 'provider_accounts'

src/app/views/pool_families/show.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  .obj_actions
    .button-group
      = link_to t('edit'), edit_pool_family_path(@pool_family), :class => 'button'
      = button_to t('delete'), pool_family_path(@pool_family), :method => :delete, :confirm => t("pool_families.confirm_delete"), :class => "button danger", :id => 'delete_pool_family_button'
  %h1.pool_families= @title

%section.content-section.pool_families
  %header#tab-container-1
    %nav.faceted
      %ul#tab-container-1-nav
        - @tabs.each do |tab|
          %li
            %a{ :href => url_for(:details_tab => tab[:id], :only_tab => true), :id => "details_#{tab[:id]}", :class => "#{'active' if @details_tab[:id] == tab[:id]} show"}
              = tab[:name]
            -if tab[:count]
              %span.label.badge.count.dark=tab[:count]
  .content#tab
    = render :partial => @view

src/app/views/pool_families/show.xml.haml
!!! XML
=render 'detail', :pool_family => pool_family