src/config/routes.rb
Conductor::Application.routes.draw do

  resource :user_sessions
  match 'login',       :to => 'user_sessions#new',     :as => 'login'
  match 'logout',      :to => 'user_sessions#destroy', :as => 'logout'
  match 'register',    :to => 'users#new',             :as => 'register'

  resource  'account', :to => 'users'

  resources :password_resets, :only => [:create, :edit, :update]
  resources :username_recoveries, :only => [:create]

  resources :templates
  resources :permissions do
    collection do
      get :list
      delete :multi_destroy
      post :multi_update
      post :filter
      post :filter_entities
      post :profile_filter
    end
  end

  resources :settings do
    collection do
      get :self_service
    end
  end
  resources :pools do
    delete :multi_destroy, :on => :collection
    post :filter, :on => :collection

    resource :provider_selection, :only => [:show] do
      resources :provider_priority_groups, :except => [:show]

      match ':strategy_name/toggle', :to => 'provider_selections#toggle_strategy', :as => 'toggle_strategy'
      match ':strategy_name/edit', :to => 'provider_selections#edit_strategy', :as => 'edit_strategy'
      match ':strategy_name/save_strategy_options', :to => 'provider_selections#save_strategy_options', :as => 'save_strategy_options'
    end
  end

  resources :deployments do
    collection do
      get 'multi_stop'
      delete :multi_destroy
      get 'launch_new'
      post 'launch_time_params'
      get 'launch_time_params'
      post 'overview'
      get 'check_name'
      get 'launch_from_catalog'
      post 'filter'
    end
    resources :instances
  end

  resources :instances do
    collection do
      get 'multi_stop'
      get 'multi_reboot'
      get 'remove_failed'
      get 'export_events'
      post 'filter'
    end
    member do
      get 'key'
      post 'stop'
      post 'reboot'
    end
    resources :instance_parameters
  end

  resources :image_imports

  resources :hardware_profiles do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
    post :matching_provider_hardware_profiles, :on => :collection
  end

  resources :providers do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection

    resources :provider_accounts do
      collection do
        delete 'multi_destroy'
        get 'set_selected_provider'
        post :filter
      end
    end
  end

  resources :provider_accounts, :only => :index

  resources :provider_types, :only => :index

  resources :users do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :user_groups do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get 'add_members'
      post 'add_members'
      delete 'remove_members'
      post 'filter_members'
    end
  end

  resources :logs do
    collection do
      post 'filter'
      get 'export_logs'
    end
  end

  resources :config_servers do
    member do
      get 'test'
    end
  end

  resources :roles do
    delete 'multi_destroy', :on => :collection
  end

  resources :pool_families do
    collection do
      delete 'multi_destroy'
      post 'add_provider_account'
    end
    member do
      get 'add_provider_accounts'
      post 'add_provider_accounts'
      post 'remove_provider_accounts'
    end
  end

  resources :frontend_realms do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :provider_realms do
    post :filter, :on => :collection
  end

  resources :realm_mappings do
    delete 'multi_destroy', :on => :collection
  end

  resources :catalogs do
    delete 'multi_destroy', :on => :collection
    post 'create'
    post :filter, :on => :collection
    resources :deployables do
      collection do
        delete 'multi_destroy'
        post :filter
      end
      member do
        get :definition
      end
    end
  end

  resources :catalog_entries

  resources :deployables do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get :definition
    end
  end

  resources :images do
    member do
      post 'rebuild_all'
      post 'push_all'
      get 'template'
    end
    collection do
      post 'edit_xml'
      post 'overview'
      delete 'multi_destroy'
      post 'import'
    end
    resources :target_images
    resources :provider_images
  end

  get 'api', :controller => 'api/entrypoint', :action => 'index'
  namespace :api do
    resources :images do
      resources :builds
    end
    resources :builds do
      resources :target_images
    end

    resources :target_images do
      resources :provider_images
    end

    resources :provider_images

    resources :hooks

    resources :environments do
      resources :images
    end
  end

  scope "/api", :as => 'api' do
    resources :providers, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :only => [:index, :create]
    end
    resources :provider_accounts, :only => [:index, :create, :show, :update, :destroy]
    resources :provider_types, :only => [:index, :show]
    resources :hardware_profiles, :only => [:index, :show, :destroy, :create]
    resources :pools, :only => [:index, :show, :create, :update, :destroy]
    resources :pool_families, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :controller => "pool_families_to_provider_accounts_associations", :only => [:index, :show, :update, :destroy]
    end
    resources :catalogs, :only => [:index, :show, :create, :update, :destroy]
    resources :provider_realms, :only => [:index, :show]
  end

  match     'dashboard', :to => 'dashboard', :as => 'dashboard'
  root      :to => "pools#index"

  match '/:controller(/:action(/:id))'
end

src/app/models/frontend_realm.rb
#
#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# == Schema Information
# Schema version: 20110207110131
#
# Table name: frontend_realms
#
#  id           :integer         not null, primary key
#  name         :string(1024)    not null
#  lock_version :integer         default(0)
#  created_at   :datetime
#  updated_at   :datetime
#

# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class FrontendRealm < ActiveRecord::Base
  class << self
    include CommonFilterMethods
  end
  has_many :realm_backend_targets, :dependent => :destroy
  has_many :instances

  # there is a problem with has_many through + polymophic in AR:
  # http://blog.hasmanythrough.com/2006/4/3/polymorphic-through
  # so we define explicitly backend_realms and backend_providers
  has_many :backend_realms, :through => :realm_backend_targets, :source => :provider_realm, :conditions => "realm_backend_targets.provider_realm_or_provider_type = 'ProviderRealm'"
  has_many :backend_providers, :through => :realm_backend_targets, :source => :provider, :conditions => "realm_backend_targets.provider_realm_or_provider_type = 'Provider'"

  validates_presence_of :name
  validates_uniqueness_of :name

  validates_length_of :description, :maximum => 255, :allow_blank => true

  PRESET_FILTERS_OPTIONS = []

  private

  def self.apply_search_filter(search)
    if search
      where("lower(frontend_realms.name) LIKE :search", :search => "%#{search.downcase}%")
    else
      scoped
    end
  end
end

src/app/controllers/frontend_realms_controller.rb
#
#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

class FrontendRealmsController < ApplicationController
  before_filter :require_user
  before_filter :load_realms, :only =>[:index, :show]

  def index
    @title = t('realms.realms')
    clear_breadcrumbs
    save_breadcrumb(frontend_realms_path)
    set_admin_content_tabs 'frontend_realms'
    respond_to do |format|
      format.html
      format.js { render :partial => 'list' }
    end
  end

  def new
    require_privilege(Privilege::CREATE, FrontendRealm)
    @realm = FrontendRealm.new
    load_backend_realms
  end

  def edit
    require_privilege(Privilege::MODIFY, FrontendRealm)
    @realm = FrontendRealm.find(params[:id])
    @title = @realm.name
    load_backend_realms
  end

  def update
    require_privilege(Privilege::MODIFY, FrontendRealm)
    @realm = FrontendRealm.find(params[:id])
    @title = @realm.name || t("realms.realm")

    if params[:commit] == "Reset"
      redirect_to edit_realm_url(@realm) and return
    end

    if @realm.update_attributes(params[:frontend_realm])
      flash[:notice] = t"realms.flash.notice.updated"
      redirect_to frontend_realms_url and return
    end

    load_backend_realms
    render :action => 'edit'
  end

  def create
    require_privilege(Privilege::CREATE, FrontendRealm)
    #@provider = Provider.find(params[:provider_id])
    @realm = FrontendRealm.new(params[:frontend_realm])
    if @realm.save
      flash[:notice] = t"realms.flash.notice.added"
      redirect_to frontend_realm_path(@realm)
    else
      load_backend_realms
      render :new
    end
  end

  def destroy
    require_privilege(Privilege::MODIFY, FrontendRealm)
    if FrontendRealm.destroy(params[:id])
      flash[:notice] = t "realms.flash.notice.deleted"
    else
      flash[:error] = t"realms.flash.error.not_deleted"
    end
    redirect_to frontend_realms_path
  end

  def multi_destroy
    deleted = []
    not_deleted = []
    if params[:realm_selected].blank?
      flash[:error] = t"realms.flash.error.select_to_delete"
    else
      FrontendRealm.find(params[:realm_selected]).each do |realm|
        require_privilege(Privilege::MODIFY, FrontendRealm)
        if realm.destroy
          deleted << realm.name
        else
          not_deleted << realm.name
        end
      end
    end

    unless deleted.empty?
      flash[:notice] = "#{t('realms.flash.notice.more_deleted')} #{deleted.join(', ')}"
    end
    unless not_deleted.empty?
      flash[:error] = "#{t('realms.flash.error.more_not_deleted')} #{not_deleted.join(', ')}"
    end
    redirect_to frontend_realms_path
  end

  def show
    @realm = FrontendRealm.find(params[:id])
    @title = @realm.name
    @tab_captions = [t('realms.tab_captions.properties'), t('realms.tab_captions.mapping')]
    @details_tab = params[:details_tab].blank? ? 'properties' : params[:details_tab]
    @details_tab = 'properties' unless ['properties', 'mapping'].include?(@details_tab)

    @backend_realm_targets = @realm.realm_backend_targets.select { |x| x.provider_realm_or_provider_type == 'ProviderRealm' }
    @backend_provider_targets = @realm.realm_backend_targets.select { |x| x.provider_realm_or_provider_type == 'Provider' }

    save_breadcrumb(frontend_realm_path(@realm), @realm.name)
    load_backend_realms

    respond_to do |format|
      format.html { render :action => 'show' }
      format.js do
        if params.delete :details_pane
          render :partial => 'layouts/details_pane' and return
        end
        render :partial => @details_tab
      end
      format.json { render :json => @realm }
    end
  end

  def filter
    redirect_to_original({"realms_preset_filter" => params[:realms_preset_filter], "realms_search" => params[:realms_search]})
  end

  protected

  def load_backend_realms
    #TODO: list only realms user has permission on
    @backend_realms = Provider.list_for_user(current_session, current_user,
                                             Privilege::USE).collect do |provider|
      provider.provider_realms
    end.flatten

    @providers = Provider.list_for_user(current_session, current_user,
                                        Privilege::USE)
  end

  def load_realms
    @header = [
      {:name => '', :sortable => false},
      {:name => t("realms.index.realm_name"), :sort_attr => :name},
    ]
    @realms = FrontendRealm.apply_filters(:preset_filter_id => params[:realms_preset_filter], :search_filter => params[:realms_search])
  end
end

src/app/views/frontend_realms/_form.html.haml
- if @realm.errors.any?
  = render 'layouts/error_messages', :object => @realm
%fieldset
  .field
    = form.label :name
    .input
      = form.text_field :name, :value => @realm.name, :class => 'em long'
  .field
    = form.label :description
    .input
      = form.text_area :description, :title => t("activerecord.attributes.frontend_realm.description"), :value => @realm.description, :class => 'long'

%fieldset.options
  = form.submit t('save'), :class => "submit button primary"
  = link_to t('cancel'), frontend_realms_path, :class => 'button danger'

src/app/views/frontend_realms/_list.html.haml
- content_for :form_header do
  -# If we add per-realm permissions, move delete permission check to controller
  -# (vs. the all-or-nothing check here)
  - if check_privilege(Privilege::MODIFY, FrontendRealm)
    - if @provider.nil?
      %li= link_to t('realms.new_realm'), new_frontend_realm_path, :id => 'new_realm_button', :class => 'button primary'
    %li= restful_submit_tag t('delete'), "destroy", multi_destroy_frontend_realms_path, 'DELETE', :id => 'delete_button', :class => 'button danger'

- content_for :filter_controls do
  %li
    = label_tag :realms_preset_filter, t('filter_table.viewing')
    = hidden_field_tag :current_path, request.fullpath
    = select_tag(:realms_preset_filter, preset_filters_options_for_select(FrontendRealm::PRESET_FILTERS_OPTIONS, params[:realms_preset_filter]), :include_blank => t("realms.preset_filters.all_realms"), :disabled => true)
    = restful_submit_tag t("filter_table.apply_filters"), "index", filter_frontend_realms_path, 'POST', :class => 'button', :id => 'apply_realms_preset_filter'
    %span.label.badge.dark= @realms.count
  %li.table-search-filter
    = text_field_tag :realms_search, params[:realms_search], :placeholder => t("filter_table.search")
    = restful_submit_tag "", "index", filter_frontend_realms_path, 'POST', :class => 'button', :id => 'apply_realms_search'

  :javascript
    $(document).ready(function(){
      $("#apply_realms_preset_filter").hide();
      $("#realms_preset_filter").change(function() {
        $("#apply_realms_preset_filter").click();
      });
      Conductor.clickOnEnterKeypress($('#realms_search'), $('#apply_realms_search'));
    });

= filter_table(realms_header, @realms) do |realm|
  %tr{:class => cycle('nostripe','stripe')}
    %td{:class => 'checkbox'}
      - selected = params[:select] == 'all'
      = check_box_tag "realm_selected[]", realm.id, selected, :id => "realm_checkbox_#{realm.id}"
    %td= link_to realm.name, frontend_realm_path(realm)

src/app/views/frontend_realms/_mapping.html.haml
= form_tag multi_destroy_realm_mappings_path(:frontend_realm_id => @realm.id) do
  %header
    - if check_privilege(Privilege::MODIFY, FrontendRealm)
      .section-controls
        - if @realm.realm_backend_targets and !@realm.realm_backend_targets.empty?
          = submit_tag t('realms.list.delete_selected'), :id => 'delete_mapping_button', :class => 'button pill danger', :confirm => t("realms.show.sure_to_delete")
        .button-group
          - if @backend_realms and !@backend_realms.empty?
            = link_to t('realms.mapping.mapping_realm'), new_realm_mapping_path(:frontend_realm_id => @realm.id, :provider_realm_or_provider_type => 'ProviderRealm'), :class => "button pill", :id => 'mapping_to_realm_button'
          - if @providers and !@providers.empty?
            = link_to t('realms.mapping.mapping_provider'), new_realm_mapping_path(:frontend_realm_id => @realm.id, :provider_realm_or_provider_type => 'Provider'), :class => "button pill", :id => 'mapping_to_provider_button'
    %h2= t'realms.show.realm_mapping'

  .content
    %fieldset
      - unless @backend_provider_targets.empty?
        %h3= t('realms.mapping.realm_mapped_providers', :name=> "#{@realm.name}")
        %table.flat.checkbox_table
          - @backend_provider_targets.each do |backend|
            %tr{:class => cycle('nostripe','stripe')}
              %td.checkbox= check_box_tag "id[]", backend.id, false, :id => "backend_id_#{backend.id}"
              %td= backend.provider_realm_or_provider.name

    %fieldset
      - unless @backend_realm_targets.empty?
        %h3= t('realms.mapping.realm_mapped_realms', :name=> "#{@realm.name}")
        %table.flat.checkbox_table
          - @backend_realm_targets.each do |backend|
            %tr{:class => cycle('nostripe','stripe')}
              %td.checkbox= check_box_tag "id[]", backend.id, false, :id => "backend_id_#{backend.id}"
              %td= "#{backend.target_provider.name}: #{backend.target_realm.name}"

src/app/views/frontend_realms/_properties.html.haml
%table.properties_table
  %tbody
    %tr
      %td= t'realms.properties.realm_name'
      %td
        = @realm.name

src/app/views/frontend_realms/edit.html.haml
= render :partial => 'layouts/admin_nav'

%header.page-header
  .obj_actions
    = link_to t('realms.new_realm'), new_frontend_realm_url, :class => 'button primary', :id => 'new_user_button'
    = link_to t('realms.edit.cancel_editing'), frontend_realm_path(@realm), :class => 'button pill danger', :id => 'new_user_button'
  %h1.realms= @title

%section.content-section.realm
  %header
    %h2= t'realms.edit.properties'

  .content
    = form_for @realm, :url => frontend_realm_path(@realm), :html => { :method => :put, :class => 'generic horizontal' } do |f|
      = render :partial => "form", :locals => { :form => f }

src/app/views/frontend_realms/index.html.haml
= render :partial => 'layouts/admin_nav'
= render :partial => 'layouts/admin_content_tabs'

src/app/views/frontend_realms/new.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  .obj_actions
    .return_to
      =t'return_to'
      = link_to t('realms.realms'), frontend_realms_path
  %h1.realms= t 'realms.new.create_realm'

%section.content-section.users
  .content
    = form_for @realm, :url => frontend_realms_path, :html => {:class => 'generic horizontal'} do |f|
      = render :partial => "form", :locals => { :form => f }

src/app/views/frontend_realms/show.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  .obj_actions
    .return_to
      =t'return_to'
      = link_to t('realms.realms'), frontend_realms_path
    - if check_privilege(Privilege::CREATE, FrontendRealm)
      = link_to t('realms.new_realm'), new_frontend_realm_url, :class => 'button primary', :id => 'new_realm_button'
    .button-group
      - if check_privilege(Privilege::MODIFY, FrontendRealm)
        = link_to t('edit'), edit_frontend_realm_path(@realm), :class => 'button pill', :id => 'edit_realm_button'
        = button_to t('delete'), frontend_realm_path(@realm), :method => :delete, :confirm => t("realms.show.sure_to_delete"), :class => 'button pill danger', :id => 'delete_realm_button'
  %h1.realms= @title

%section.content-section.realm
  %header
    %h2= t'realms.show.properties'

  .content
    = render :partial => 'properties'

%section.content-section.realm_mapping
  = render :partial => 'mapping'