src/config/routes.rb
Conductor::Application.routes.draw do

  resource :user_sessions
  match 'login',       :to => 'user_sessions#new',     :as => 'login'
  match 'logout',      :to => 'user_sessions#destroy', :as => 'logout'
  match 'register',    :to => 'users#new',             :as => 'register'

  resource  'account', :to => 'users'

  resources :password_resets, :only => [:create, :edit, :update]
  resources :username_recoveries, :only => [:create]

  resources :templates
  resources :permissions do
    collection do
      get :list
      delete :multi_destroy
      post :multi_update
      post :filter
      post :filter_entities
      post :profile_filter
    end
  end

  resources :settings do
    collection do
      get :self_service
    end
  end
  resources :pools do
    delete :multi_destroy, :on => :collection
    post :filter, :on => :collection

    resource :provider_selection, :only => [:show] do
      resources :provider_priority_groups, :except => [:show]

      match ':strategy_name/toggle', :to => 'provider_selections#toggle_strategy', :as => 'toggle_strategy'
      match ':strategy_name/edit', :to => 'provider_selections#edit_strategy', :as => 'edit_strategy'
      match ':strategy_name/save_strategy_options', :to => 'provider_selections#save_strategy_options', :as => 'save_strategy_options'
    end
  end

  resources :deployments do
    collection do
      get 'multi_stop'
      delete :multi_destroy
      get 'launch_new'
      post 'launch_time_params'
      get 'launch_time_params'
      post 'overview'
      get 'check_name'
      get 'launch_from_catalog'
      post 'filter'
    end
    resources :instances
  end

  resources :instances do
    collection do
      get 'multi_stop'
      get 'multi_reboot'
      get 'remove_failed'
      get 'export_events'
      post 'filter'
    end
    member do
      get 'key'
      post 'stop'
      post 'reboot'
    end
    resources :instance_parameters
  end

  resources :image_imports

  resources :hardware_profiles do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
    post :matching_provider_hardware_profiles, :on => :collection
  end

  resources :providers do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection

    resources :provider_accounts do
      collection do
        delete 'multi_destroy'
        get 'set_selected_provider'
        post :filter
      end
    end
  end

  resources :provider_accounts, :only => :index

  resources :provider_types, :only => :index

  resources :users do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :user_groups do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get 'add_members'
      post 'add_members'
      delete 'remove_members'
      post 'filter_members'
    end
  end

  resources :logs do
    collection do
      post 'filter'
      get 'export_logs'
    end
  end

  resources :config_servers do
    member do
      get 'test'
    end
  end

  resources :roles do
    delete 'multi_destroy', :on => :collection
  end

  resources :pool_families do
    collection do
      delete 'multi_destroy'
      post 'add_provider_account'
    end
    member do
      get 'add_provider_accounts'
      post 'add_provider_accounts'
      post 'remove_provider_accounts'
    end
  end

  resources :frontend_realms do
    delete 'multi_destroy', :on => :collection
    post :filter, :on => :collection
  end

  resources :provider_realms do
    post :filter, :on => :collection
  end

  resources :realm_mappings do
    delete 'multi_destroy', :on => :collection
  end

  resources :catalogs do
    delete 'multi_destroy', :on => :collection
    post 'create'
    post :filter, :on => :collection
    resources :deployables do
      collection do
        delete 'multi_destroy'
        post :filter
      end
      member do
        get :definition
      end
    end
  end

  resources :catalog_entries

  resources :deployables do
    collection do
      delete 'multi_destroy'
      post :filter
    end
    member do
      get :definition
    end
  end

  resources :images do
    member do
      post 'rebuild_all'
      post 'push_all'
      get 'template'
    end
    collection do
      post 'edit_xml'
      post 'overview'
      delete 'multi_destroy'
      post 'import'
    end
    resources :target_images
    resources :provider_images
  end

  get 'api', :controller => 'api/entrypoint', :action => 'index'
  namespace :api do
    resources :images do
      resources :builds
    end
    resources :builds do
      resources :target_images
    end

    resources :target_images do
      resources :provider_images
    end

    resources :provider_images

    resources :hooks

    resources :environments do
      resources :images
    end
  end

  scope "/api", :as => 'api' do
    resources :providers, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :only => [:index, :create]
    end
    resources :provider_accounts, :only => [:index, :create, :show, :update, :destroy]
    resources :provider_types, :only => [:index, :show]
    resources :hardware_profiles, :only => [:index, :show, :destroy, :create]
    resources :pools, :only => [:index, :show, :create, :update, :destroy]
    resources :pool_families, :only => [:index, :show, :create, :update, :destroy] do
      resources :provider_accounts, :controller => "pool_families_to_provider_accounts_associations", :only => [:index, :show, :update, :destroy]
    end
    resources :catalogs, :only => [:index, :show, :create, :update, :destroy]
    resources :provider_realms, :only => [:index, :show]
  end

  match     'dashboard', :to => 'dashboard', :as => 'dashboard'
  root      :to => "pools#index"

  match '/:controller(/:action(/:id))'
end

src/app/controllers/deployables_controller.rb
#
#   Copyright 2011 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
require 'uri'

class DeployablesController < ApplicationController
  before_filter :require_user

  def index
    clear_breadcrumbs
    if params[:catalog_id].present?
      save_breadcrumb(catalog_deployables_path(:viewstate => @viewstate ? @viewstate.id : nil))
      @catalog = Catalog.find(params[:catalog_id])
      @deployables = @catalog.deployables
      @catalog_entries = @deployables.collect { |d| d.catalog_entries.first }
    else
      save_breadcrumb(deployables_path)
      @deployables = Deployable.without_catalog.
        list_for_user(current_session, current_user, Privilege::VIEW)
    end
    set_header
  end

  def new
    @deployable = Deployable.new(params[:deployable])
    if params[:create_from_image]
      # TODO - pass id instead of uuid once links pointing to this action are
      # fixed
      @image = Tim::BaseImage.find(params[:create_from_image])
      @hw_profiles = HardwareProfile.frontend.
        list_for_user(current_session, current_user, Privilege::VIEW)
      @deployable.name = @image.name
      @selected_catalogs = Array(params[:catalog_id])
      load_catalogs
      @selected_catalogs.each do |catalog_id|
        require_privilege(Privilege::CREATE, Deployable, Catalog.find_by_id(catalog_id))
      end
      flasherr = []
      flasherr << t("deployables.flash.error.no_catalog_exists") if @catalogs.empty?
      flasherr << t("deployables.flash.error.no_hwp_exists") if @hw_profiles.empty?
      @save_disabled = !(flasherr.empty?)
      flash[:error] = flasherr if not flasherr.empty?
    elsif params[:catalog_id].present?
      @catalog = Catalog.find(params[:catalog_id])
      require_privilege(Privilege::CREATE, @catalog, Deployable)
    end
    @form_option= params.has_key?(:from_url) ? 'from_url' : 'upload'
    respond_to do |format|
        format.html
        format.js {render :partial => @form_option}
    end
  end

  def show
    @deployable = Deployable.find(params[:id])
    @catalog = params[:catalog_id].present? ? Catalog.find(params[:catalog_id]) : @deployable.catalogs.first
    require_privilege(Privilege::VIEW, @deployable)
    save_breadcrumb(polymorphic_path([@catalog, @deployable]), @deployable.name)
    @providers = Provider.all
    @catalogs_options = Catalog.list_for_user(current_session, current_user,
                                              Privilege::MODIFY).select do |c|
      !@deployable.catalogs.include?(c) and
        @deployable.catalogs.first.pool_family == c.pool_family
    end

    if @catalog.present?
      add_permissions_inline(@deployable, '', {:catalog_id => @catalog.id})
    else
      add_permissions_inline(@deployable)
    end

    @images_details, images, @missing_images, @deployable_errors = @deployable.get_image_details
    flash.now[:error] = @deployable_errors unless @deployable_errors.empty?

    if @missing_images.empty?
      @image_status = []
      @pushed_count = 0

      @deployable.pool_family.provider_accounts.includes(:provider).
                  where('providers.enabled' => true).each do |provider_account|
        deltacloud_driver =
          provider_account.provider.provider_type.deltacloud_driver
        build_status = @deployable.build_status(images, provider_account)
        @pushed_count += 1 if (build_status == :pushed)

        @image_status << {
          :deltacloud_driver => deltacloud_driver,
          :provider_account_label => provider_account.label,
          :provider_name => provider_account.provider.name,
          :build_status => build_status,
          :translated_build_status =>
            t("deployables.show.build_statuses_descriptions.#{build_status}")
        }

        @image_status.sort_by do |image_status_for_account|
          image_status_for_account[:deltacloud_driver]
        end
      end
    end

    respond_to do |format|
      format.html
      format.json do
        render :json => { :image_status => @image_status }
      end
    end

  end

  def definition
    @deployable = Deployable.find(params[:id])
    require_privilege(Privilege::VIEW, @deployable)
    render :xml => @deployable.xml
  end

  def create
    if params[:cancel]
      redirect_to polymorphic_path([params[:catalog_id], Deployable])
      return
    end

    @deployable = Deployable.new(params[:deployable])
    @selected_catalogs = Catalog.find(Array(params[:catalog_id]))
    @deployable.owner = current_user
    @selected_catalogs.each do |catalog|
      require_privilege(Privilege::CREATE, Deployable, catalog)
    end

    if params.has_key? :url
      xml, error = import_xml_from_url(params[:url])
      unless xml.nil?
        #store xml_filename for url (i.e. url ends to: foo || foo.xml)
        @deployable.xml_filename =  File.basename(URI.parse(params[:url]).path)
        @deployable.xml = xml
      end
    elsif params[:create_from_image].present?
      hw_profile = HardwareProfile.frontend.find(params[:hardware_profile])
      require_privilege(Privilege::VIEW, hw_profile)
      @deployable.set_from_image(params[:create_from_image], params[:deployable][:name], hw_profile)
    end

    begin
      raise t("deployables.flash.error.no_catalog") if @selected_catalogs.empty?
      @deployable.transaction do
        @selected_catalogs.each do |catalog|
          @deployable.catalogs << catalog
        end
        @deployable.save!
        flash[:notice] = t("catalog_entries.flash.notice.added", :catalog => @selected_catalogs.map{|c| c.name}.join(", "))
        if params[:edit_xml]
          redirect_to edit_polymorphic_path([@selected_catalogs.first, @deployable], :edit_xml =>true)
        elsif params[:create_from_image]
          redirect_to @deployable
        else
          redirect_to catalog_path(@selected_catalogs.first)
        end
      end

      # check that type attrs on service params are used properly
      warnings = @deployable.check_service_params_types
      unless warnings.empty?
        flash[:warning] ||= []
        flash[:warning] = [flash[:warning]] if flash[:warning].kind_of? String
        flash[:warning]+=warnings
      end

    rescue => e
      @deployable.errors.add(:url, error) if error
      if @deployable.errors.empty?
        logger.error e.message
        logger.error e.backtrace.join("\n ")
        flash.now[:warning]= t('deployables.flash.warning.failed', :message => e.message)
      end
      if params[:create_from_image].present?
        @image = Tim::BaseImage.find(params[:create_from_image])
        load_catalogs
        @hw_profiles = HardwareProfile.frontend.
          list_for_user(current_session, current_user, Privilege::VIEW)
      else
        @catalog = @selected_catalogs.first
        params.delete(:edit_xml) if params[:edit_xml]
        @form_option = params[:form_option].eql?('upload') ? 'upload' : 'from_url'
      end
      render :new
    end
  end

  def edit
    @deployable = Deployable.find(params[:id])
    require_privilege(Privilege::MODIFY, @deployable)
    @catalog = Catalog.find(params[:catalog_id]) if params[:catalog_id].present?
  end

  def update
    @deployable = Deployable.find(params[:id])
    @catalog = Catalog.find(params[:catalog_id]) if params[:catalog_id].present?
    require_privilege(Privilege::MODIFY, @deployable)
    params[:deployable].delete(:owner_id) if params[:deployable]

    if @deployable.update_attributes(params[:deployable])
      # check that type attrs on service params are used properly
      warnings = @deployable.check_service_params_types
      unless warnings.empty?
        flash[:warning] ||= []
        flash[:warning] = [flash[:warning]] if flash[:warning].kind_of? String
        flash[:warning]+=warnings
      end

      flash[:notice] = t"catalog_entries.flash.notice.updated"
      redirect_to polymorphic_path([@catalog, @deployable])
    else
      render :action => 'edit', :edit_xml => params[:edit_xml]
    end
  end

  # the name here is confusing; we may want to rename to multi_remove at some point
  def multi_destroy
    deleted = []
    not_deleted = []
    not_deleted_perms = []

    @catalog = Catalog.find(params[:catalog_id])

    if params[:deployables_selected]
      Deployable.find(params[:deployables_selected]).to_a.each do |d|
        if check_privilege(Privilege::MODIFY, d)
          if d.catalog_entries.where(:catalog_id => @catalog.id).first.destroy
            deleted << d.name
          else
            not_deleted << d.name
          end
        else
          not_deleted_perms << d.name
        end
      end
      unless not_deleted.empty? and not_deleted_perms.empty?
        flasherr = []
        flasherr =  t("deployables.flash.error.not_deleted", :count => not_deleted.count, :not_deleted => not_deleted.join(', ')) unless not_deleted.empty?
        flasherr =  t("deployables.flash.error.not_deleted_perms", :count => not_deleted_perms.count, :not_deleted => not_deleted_perms.join(', ')) unless not_deleted_perms.empty?
        flash[:error] = flasherr
      end
      flash[:notice] = t("deployables.flash.notice.deleted", :count => deleted.count, :deleted => deleted.join(', ')) unless deleted.empty?
    else
      flash[:error] = t("deployables.flash.error.not_selected")
    end

    if @catalog.present?
      redirect_to catalog_path(@catalog)
    else
      redirect_to deployables_path
    end
  end

  def destroy
    deployable = Deployable.find(params[:id])

src/app/helpers/deployables_helper.rb
module DeployablesHelper
  def image_valid?(assembly, modify_perm)
    edit_xml_path = edit_polymorphic_path([@catalog, @deployable], :edit_xml => true)

    if @missing_images.empty? && assembly[:hwp_name].present?
      link_hash = {:label => '.images_valid', :class => 'images_valid'}
    elsif assembly[:hwp_name].nil?
      link_hash = {:label => '.repair_images', :class => 'repair_images'}
    elsif @missing_images.include?(assembly[:image_uuid])
      link_hash = {:label => '.repair_images', :class => 'repair_images'}
    else
      link_hash = {:label => '.images_valid', :class => 'images_valid'}
    end
    if modify_perm
      link_to(t(link_hash[:label]), edit_xml_path,
              :class => link_hash[:class], :id => 'edit_xml_button')
    else
      content_tag(:a, t(link_hash[:label]), :class => link_hash[:class],
                  :id => 'edit_xml_button')
    end
  end

  def deployable_ready?
    false
  end
end

src/app/views/deployables/_assemblies.haml
.grid_13
- form_tag do
  = restful_submit_tag "Remove Selected", 'destroy', remove_assemblies_deployable_path(@deployable), 'DELETE', :id => 'delete_button'
  = link_to "Add Assembly...", pick_assemblies_deployable_path(@deployable), :class => 'button', :id => 'add_assembly'

  %table#assemblies_table
    %thead
      %tr
        %th
        %th= "Name"
        %th= "Created"
    -@deployable.assemblies(:include => :templates).each do |assembly|
      %tr
        %td
          %input{:name => "assemblies_selected[]", :type => "checkbox", :value => assembly.id, :id => "assembly_checkbox_#{assembly.id}" }
        %td= assembly.name
        %td= assembly.created_at

:javascript
  $(document).ready(function () {
    $('#add_assembly').click(function(e) {
      e.preventDefault();
      var url = $(this).attr('href');
      $.get(url, function(data) {
        var selectedTabIndex = $("#details-view").tabs('option', 'selected');
        var $selectedTab = $("#details-view div.ui-tabs-panel").eq(selectedTabIndex);
        $selectedTab.html(data);
      });
    });
  });

src/app/views/deployables/_form.haml
= form.error_messages
%fieldset.clear
  = form.label :name, t(:name), :class => "grid_3 alpha"
  = form.text_field :name, :class => "grid_5"
%fieldset.clear
  = form.label :summary, t(:summary), :class => "grid_3 alpha"
  = form.text_area :summary, :class => "grid_5", :rows => 3
%fieldset.clearfix
  = form.submit "Save",  :class => "submit formbutton"
  = link_to t(:cancel), deployables_path, :class => 'button formbutton'

src/app/views/deployables/_image_uuids.html.haml
%table.light_table
  %tbody
    %tr
      %td
        %strong="#{t("deployables.show.image_uuid")}"
      %td
        ="#{(uuid_arr[0].nil? ? t('deployables.show.n_a') : uuid_arr[0])}"
    %tr
      %td
        %strong="#{t("deployables.show.latest_build_uuid")}"
      %td
        ="#{(uuid_arr[1].nil? ? t("deployables.show.n_a") : uuid_arr[1])}"
    %tr
      %td
        %strong="#{t("deployables.show.target_images_uuids")}"
      %td
        - if uuid_arr[2].nil?
          =t'deployables.show.n_a'
        - else
          %ul
            - uuid_arr[2].each do |image_uuid|
              %li
                =image_uuid

src/app/views/deployables/_list.haml
- form_tag do
  = link_to "Create", new_deployable_url, :class => 'button'
  = restful_submit_tag "Delete", 'destroy', multi_destroy_deployables_path, 'DELETE', :id => 'delete_button'

  %table#deployables_table
    %thead
      %tr
        %th
        %th= link_to "Name", deployables_url(:sort_by => "name")
    -@deployables.each do |deployable|
      %tr
        %td
          %input{:name => "deployables_selected[]", :type => "checkbox", :value => deployable.id, :id => "deployable_checkbox_#{deployable.id}" }
        %td= link_to deployable.name, deployable_path(deployable)

:javascript
  $(document).ready(function () {
    $('#delete_button').click(function(e) {
      if ($("#deployables_table input[@type=radio]:checked").length == 0) {
        alert('Please select any deployable to be deleted before clicking Delete button.');
        e.preventDefault();
      } else {
        if (!confirm("Are you sure you want to delete this deployable?")) {
          e.preventDefault();
        }
      }
    });
  });

src/app/views/deployables/_new_from_image.html.haml
%header.page-header
  %h1.no-icon= @deployable.name.blank? ? "&nbsp;".html_safe : t('.catalog_entry_name', :name => @deployable.name)

%section.content-section
  .content
    = form_for @deployable, :html => {:class => 'generic horizontal'} do |form|
      = hidden_field_tag :create_from_image, params[:create_from_image]
      - if @deployable.errors.any?
        = render 'layouts/error_messages', :object => @deployable
      .lefted.new-catalog-entry-from-image
        %h2= t('.title')
        %p= t('.description', :name => @image.name)
        %fieldset
          .field
            = form.label :name, :class => 'em'
            .input
              = form.text_field :name, :class => 'em'
          .field
            = form.label :hardware_profile, t('catalog_entries.new.hw_profile')
            .input
              = select_tag :hardware_profile, options_from_collection_for_select(@hw_profiles, :id, :name, params[:hardware_profile])
          .field
            = form.label :catalog_id, t('deployables.form.catalog')
            .input
              %span.text_instead_input#checked_catalogs_list{ "data-none" => t('deployables.form.none'), "data-multiple" => t('deployables.form.multiple') }
                = @selected_catalogs.empty? ? t('deployables.form.none') : @selected_catalogs.count > 1 ? t('deployables.form.multiple') : @selected_catalogs.first.name
              %span.catalog_link
                &nbsp
                %div.catalog_list
                  %ul.more
                    - if @catalogs.empty?
                      = t('deployables.new_from_image.no_available_catalog')
                    - else
                      - @catalogs.each do |catalog|
                        %li.catalog
                          .catalog_with_checkbox
                            = check_box_tag 'catalog_id[]', catalog.id, @selected_catalogs.any?{|c| c.id == catalog.id}
                            = catalog.name

      %fieldset.options.align-center
        = submit_tag "#{t'deployables.form.save'}", :name => 'save', :class => 'button primary', :id => 'save_button', :disabled => @save_disabled
        = link_to t('deployables.form.cancel'), catalogs_path, :class => 'button danger'

:javascript
  function listChecked() {
    var $checked_catalogs_list = $("#checked_catalogs_list");
    $checked_catalogs_list.text(function(){
      var str = [];
      $(".catalog_list input:checked").each(function(){
        str.push($(this).parent().text());
      });
      if (str.length > 1){
        return $checked_catalogs_list.data('multiple');
      }else if (str.length == 0){
        return $checked_catalogs_list.data('none');
      }else{
        return str.join(', ');
      }
    });
  }
  listChecked();
  $(".catalog_list :checkbox").click(listChecked);

src/app/views/deployables/_pick_assemblies.haml
.grid_13
  - form_tag(deployable_path(@deployable)) do
    %table#assemblies_list
      %thead
        %tr
          %th
          %th= "Name"
      -@assemblies.each do |assembly|
        %tr
          %td
            %input{:name => "assemblies_selected[]", :type => "checkbox", :value => assembly.id, :id => "assembly_checkbox_#{assembly.id}" }
          %td= assembly.name

    -# AJAX post
    = restful_submit_tag('Save', 'add_assemblies', add_assemblies_deployable_path(@deployable), 'PUT')
    = link_to "Back", deployable_path(@deployable, :details_tab => 'assemblies'), :class => 'button'

src/app/views/deployables/_properties.haml
.grid_13
  %h2 #{@deployable.name}

  = link_to 'Edit', edit_deployable_path(@deployable), :class => 'button'
  - if @deployable.launchable?
    = link_to "Launch", new_deployment_path(:deployable_id => @deployable.id), {:class => 'button'}
  - else
    The deployable can't be launched - the deployable must have at least one assembly and each assembly must have at least one template.

src/app/views/deployables/edit.html.haml
= render :partial => 'layouts/admin_nav'
%header.page-header
  %h1.catalog_entries= @deployable.name

%section.content-section.user
  %header
    %h2=t'catalog_entries.edit.editing_catalog_entry'

  .content
    = form_for @deployable, :url => polymorphic_path([@catalog, @deployable]), :html => { :method => :put, :class => params[:edit_xml] ? "generic" : "generic horizontal" } do |f|
      = render :partial => "form", :locals => { :form => f }

src/app/views/deployables/new.haml
%h2 New Deployable
- form_for @deployable, :url => deployables_path do |f|
  = render :partial => "form", :locals => { :form => f }

src/app/views/deployables/new.html.haml
= render :partial => 'layouts/admin_nav'
= render :partial => params[:create_from_image] ? 'new_from_image' : 'new'

src/app/views/deployables/show.html.haml
= render :partial => 'layouts/admin_nav'
- modify_perm = check_privilege(Privilege::MODIFY, @deployable)
%header.page-header
  .obj_actions
    .button-group
      - if modify_perm
        = link_to t('.edit'), edit_polymorphic_path([@catalog, @deployable]), :class => 'button', :id => 'edit_button'
        = link_to t('.edit_xml'), edit_polymorphic_path([@catalog, @deployable], :edit_xml => true), :class => 'button', :id => 'edit_xml_button'
        = button_to t('.delete'), polymorphic_path([@catalog, @deployable]), :method => 'delete', :confirm => "#{t'catalog_entries.show.confirm_delete'}", :class => 'button danger', :id => 'delete'

    - launch_deployment_button_path = launch_new_deployments_path(:deployable_id => @deployable.id, :deployment => { :name => @deployable.name, :pool_id => @catalog.pool }, :backlink => request.fullpath)
    - if @catalog.present? && @deployable_errors.empty? && @pushed_count > 0
      = link_to t('.launch'), launch_deployment_button_path, :id => :launch_deployment_button, :'data-path' => launch_deployment_button_path
    -else
      %a{:id => :launch_deployment_button, :class => 'disabled', :'data-path' => launch_deployment_button_path}= t('.launch')
  %h1.catalog_entries= @deployable.name

%section.content-section
  %header
    %h2.images= t('.images')
  .content
    %table.light_table
      %thead
        %tr
          %th.status
          %th
            %strong=t'.name'
          %th.align-center=t'.images'
          %th=t'.hw_profile'
          %th.align-center=t'.hdd'
          %th.align-center=t'.ram'
          %th.align-center=t'.arch'
          %th=t(".uuids")
      %tbody
        - @images_details.each do |assembly|
          %tr
            %td.status= image_valid?(assembly, modify_perm)
            %td
              %strong=assembly[:name]
            %td.align-center=assembly[:images_count]
            %td=assembly[:hwp_name]
            %td.align-center=assembly[:hwp_hdd]
            %td.align-center=assembly[:hwp_ram]
            %td.align-center=assembly[:hwp_arch]
            %td.align-center
              - if assembly[:build_and_target_uuids].nil?
                = t(".n_a")
              - else
                %a.control{:href => '#'}=t(".show_hide_uuids")
          - unless assembly[:build_and_target_uuids].nil?
            %tr.collapsed
              %td
              %td{:colspan => 7}
                %ul
                  = render :partial => "image_uuids", :locals => {:uuid_arr => assembly[:build_and_target_uuids]}

%section.content-section
  - if @missing_images.empty?
    %header
      %h2.build= t('.build_status')

    .content
      %ul#providers-list.catalog_pretty
        - @image_status.each do |image_status_for_account|
          = render :partial => 'image_status',
                   :mustache => image_status_for_account
  - else
    %header
      %h2.build= t('.build_status')
    .content
      .centered.align-center
        %strong Assemblies in Deployable XML arent properly configured.
      %strong= t('.missing_images')
      %ul#missing-images-list
        - @missing_images.each do |uuid|
          %li= uuid

%section.content-section
  %header
    .section-controls
      -if modify_perm
        = form_for(:catalog_entry, :url => catalog_entries_path) do |f|
          = f.label :catalog_id, t('.choose_catalog')
          = f.select :catalog_id, options_for_select(@catalogs_options.map {|c| [c.name, c.id]})
          = f.hidden_field(:deployable_id, :value => @deployable.id)
          = f.submit t('.add_catalog'), :id => :add_catalog, :class => 'button primary', :disabled => @catalogs_options.empty?
    %h2.catalogs= t('.catalogs')
  .content
    .centered
      %table.light_table
        %tr
          %th.remove_catalog
          %th
            %label
              %strong= t('.catalog_name')
          %th
            %label
              %strong= t('.environment')
        - @deployable.catalog_entries.each do |catalog_entry|
          %tr
            %td.remove_catalog= button_to "", catalog_entry_path(catalog_entry), :method => 'delete', :confirm => "#{t'catalog_entries.show.confirm_delete'}", :id => 'delete', :class => 'remove_catalog'
            %td= catalog_entry.catalog.name
            %td= catalog_entry.catalog.pool.pool_family.name

- if check_privilege(Privilege::PERM_VIEW,@permission_object)
  %section.content-section
    %header
      %h2.roles= t('role_assignments')
    .content
      = render :partial => 'permissions/permissions'

:javascript
  $(document).ready(function() {
    $('table.light_table tbody tr').map(function(){
      var this_row = this;
      $(this).find('a.control').click(function(){
        $(this_row).next().toggleClass('collapsed');
        return false;
      });
    });
  });

%script#imageStatusTemplate{ :type => 'text/html' }
  = render :partial => 'image_status'